<#
.SYNOPSIS
    Commits generated/updated test files and opens a GitHub pull request.

.DESCRIPTION
    Intended to run only after TestForge AI has generated tests in the working tree
    AND the user has explicitly approved committing/pushing/opening a PR. This script
    never runs automatically as part of test generation.

    Requires:
      - git available on PATH, current directory inside the target git repository
      - GitHub CLI (`gh`) installed and authenticated (`gh auth login`), OR a
        GITHUB_TOKEN environment variable that `gh` can use non-interactively.

.PARAMETER Branch
    Name of the new branch to create for the change. Defaults to a timestamped
    "testforge/tests-<timestamp>" name if not supplied.

.PARAMETER Base
    Base branch to target for the PR. Defaults to "main".

.PARAMETER CommitMessage
    Commit message for the generated test changes.

.PARAMETER Title
    Pull request title. Defaults to the commit message.

.PARAMETER Body
    Pull request body/description.

.PARAMETER Draft
    Open the PR as a draft.

.PARAMETER Paths
    Specific file paths to stage. Defaults to staging all changes ("-A") if omitted.

.EXAMPLE
    .\create-github-pr.ps1 -CommitMessage "Add tests for login form" -Body "Generated by TestForge AI"

.EXAMPLE
    .\create-github-pr.ps1 -Branch "testforge/login-tests" -Base "develop" -Draft -Paths "src/login/*.test.tsx"
#>
[CmdletBinding()]
param(
    [string]$Branch,
    [string]$Base = "main",
    [Parameter(Mandatory = $true)]
    [string]$CommitMessage,
    [string]$Title,
    [string]$Body = "Generated by TestForge AI.",
    [switch]$Draft,
    [string[]]$Paths
)

$ErrorActionPreference = "Stop"

function Assert-Command($name) {
    if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
        throw "Required command '$name' was not found on PATH."
    }
}

Assert-Command git
Assert-Command gh

# Confirm we are inside a git repo with a work tree.
git rev-parse --is-inside-work-tree *> $null
if ($LASTEXITCODE -ne 0) {
    throw "Current directory is not inside a git repository."
}

if (-not $Branch) {
    $Branch = "testforge/tests-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
}
if (-not $Title) {
    $Title = $CommitMessage
}

$status = git status --porcelain
if ([string]::IsNullOrWhiteSpace($status)) {
    throw "No changes detected in the working tree. Nothing to commit."
}

Write-Host "Creating branch '$Branch' from current HEAD..."
git checkout -b $Branch

if ($Paths) {
    git add -- $Paths
}
else {
    git add -A
}

git commit -m $CommitMessage

Write-Host "Pushing branch '$Branch'..."
git push -u origin $Branch

$draftFlag = @()
if ($Draft) { $draftFlag = @("--draft") }

Write-Host "Opening pull request against '$Base'..."
gh pr create --base $Base --head $Branch --title $Title --body $Body @draftFlag

Write-Host "Pull request created successfully."
